# Generated by Django 4.2.7 on 2025-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('issuer', models.CharField(max_length=100, verbose_name='Выдан')),
                ('date', models.CharField(max_length=50, verbose_name='Дата')),
                ('image', models.ImageField(upload_to='certificates/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение')),
                ('technologies', models.CharField(max_length=255, verbose_name='Технологии')),
                ('demo_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на демо')),
                ('code_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на код')),
                ('featured', models.BooleanField(default=False, verbose_name='Избранный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень (0-100)')),
                ('category', models.CharField(choices=[('language', 'Язык программирования'), ('framework', 'Фреймворк/библиотека'), ('tool', 'Инструмент/технология')], max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
