# Generated by Django 4.2.7 on 2025-05-20 13:58

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date'], 'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_sent'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_created'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-level'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AddField(
            model_name='certificate',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на сертификат'),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата отправки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Веб-разработка'), ('mobile', 'Мобильные приложения'), ('desktop', 'Десктопные приложения'), ('other', 'Другое')], default='web', max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='preview_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание для предпросмотра'),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='projects/thumbnails/', verbose_name='Миниатюра'),
        ),
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(default='from-blue-500 to-blue-700', max_length=50, verbose_name='Цвет градиента'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(max_length=200, verbose_name='Выдан'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='projects/', verbose_name='Изображение проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(max_length=200, verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Языки программирования'), ('framework', 'Фреймворки и библиотеки'), ('tool', 'Инструменты и технологии')], default='language', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(default=80, verbose_name='Уровень (0-100)'),
        ),
    ]
