# Generated by Django 4.2.7 on 2025-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificate_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='preview_url',
            field=models.URLField(blank=True, help_text='URL для встроенного предпросмотра проекта (например, GitHub Pages)', verbose_name='URL для предпросмотра'),
        ),
    ]
